---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  chef_omnibus_url: http://artifactory.trusted.visa.com:8080/visa-file/chef/install.sh
  roles_path: "test/integration/visa_pipeline/roles"
  environments_path: "test/integration/visa_pipeline/environments"
  data_bags_path: "test/integration/visa_pipeline/data_bags"


platforms:
  - name: ubuntu-12.04
  - name: centos-6.4

suites:
  - name: ncurses
    run_list:
      - recipe[ncurses::default]
    attributes:
