name 'poise_archive'
version '1.3.0'
description 'A Chef cookbook for unpacking file archives like tar and zip.'
long_description ''
maintainer 'YOUR_COMPANY_NAME'
maintainer_email 'YOUR_EMAIL'
license 'none'

source_url 'https://github.com/poise/poise-archive'
issues_url 'https://github.com/poise/poise-archive/issues'