---
driver_plugin: vagrant

platforms:
- name: ubuntu-12.04
- name: ubuntu-10.04
- name: centos-6.5
- name: centos-5.10

suites:
- name: default
  data_bag_path: "test/integration/default/data_bags"
  encrypted_data_bag_secret_key_path: "test/integration/default/encrypted_data_bag_secret"
  run_list: ["recipe[certificate::manage_by_attributes]"]
  attributes:
    certificate: [
      test: {
        nginx_cert: true,
        cert_file: "test.pem",
        key_file: "test.key"
      }
    ]
