driver:
  name: vagrant

provisioner:
  name: chef_zero
  chef_omnibus_url: http://artifactory.trusted.visa.com:8080/visa-file/chef/install.sh
  roles_path: "test/integration/visa_pipeline/roles"
  environments_path: "test/integration/visa_pipeline/environments"
  data_bags_path: "test/integration/visa_pipeline/data_bags"


platforms:
  - name: centos-5.10
  - name: centos-6.5
  - name: centos-7.0
  - name: debian-6.0.10
  - name: debian-7.7
  - name: fedora-19
  - name: fedora-20
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:
  - name: rsyslog
    run_list:
      - recipe[rsyslog::default]
  - name: relp
    run_list:
      - recipe[rsyslog::default]
    attributes:
      rsyslog:
        use_relp: true
    # CentOS and OmniOS do not support relp
    excludes:
      - centos-5.8
      - omnios-r151006c
  - name: client
    run_list:
      - recipe[rsyslog::client]
    attributes:
      rsyslog:
        server_ip: 10.0.0.50
  - name: server
    run_list:
      - recipe[rsyslog::server]
