---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    run_list:
    - recipe[apt]
  - name: centos-6.4
    run_list:
    - recipe[yum-epel]

suites:
  - name: default
    data_bags_path: "test/kitchen/data_bags"
    encrypted_data_bag_secret_key_path: "test/kitchen/encrypted_data_bag_secret"
    run_list:
      - recipe[ssl_certificate_test::default]
    attributes:
