---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  chef_omnibus_url: http://artifactory.trusted.visa.com:8080/visa-file/chef/install.sh
  roles_path: "test/integration/visa_pipeline/roles"
  environments_path: "test/integration/visa_pipeline/environments"
  data_bags_path: "test/integration/visa_pipeline/data_bags"


platforms:
  - name: ubuntu-12.04
    run_list:
    - recipe[apt]
  - name: centos-6.4
    run_list:
    - recipe[yum-epel]

suites:
  - name: ssl_certificate_test
    data_bags_path: "test/kitchen/data_bags"
    encrypted_data_bag_secret_key_path: "test/kitchen/encrypted_data_bag_secret"
    run_list:
      - recipe[ssl_certificate_test::default]
    attributes:
