AllCops:
  Exclude:
    - vendor/bundle/**/*
Encoding:
  Enabled: False
LineLength:
  Max: 200
HashSyntax:
  Enabled: False
SingleSpaceBeforeFirstArg:
  Enabled: false
AsciiComments:
  Enabled: false
