AllCops:
  Exclude:
    - vendor/**

AlignParameters:
  Enabled: false
Encoding:
  Enabled: false

LineLength:
  Max: 200

HashSyntax:
  Exclude:
    - Rakefile
  EnforcedStyle: hash_rockets

MethodLength:
  Enabled: false

Style/SingleSpaceBeforeFirstArg:
  Exclude:
    - Rakefile
    - metadata.rb

Style/PercentLiteralDelimiters:
  Exclude: 
    - metadata.rb
