---
driver:
  name: docker
driver_config:
  use_sudo: false

provisioner:
  name: chef_zero
  chef_omnibus_url: http://artifactory.trusted.visa.com:8080/visa-file/chef/install.sh
  roles_path: "test/integration/visa_pipeline/roles"
  environments_path: "test/integration/visa_pipeline/environments"
  data_bags_path: "test/integration/visa_pipeline/data_bags"


platforms:
  - name: centos-6.4
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: debian-7.4

suites:
  - name: augeas
    run_list:
      - recipe[augeas::geminstall]
      - recipe[augeas::test]
    attributes:
