#<% require 'kitchen-sync' %>
---
driver_config:
  digitalocean_client_id: <%= ENV['DIGITAL_OCEAN_CLIENT_ID'] %>
  google_client_email: <%= ENV['GOOGLE_CLIENT_EMAIL'] %>
  google_key_location: <%= ENV['GOOGLE_KEY_LOCATION'] %>
  google_project: <%= ENV['GOOGLE_PROJECT'] %>
  joyent_username: <%= ENV['SDC_CLI_ACCOUNT'] %>
  joyent_keyfile: <%= ENV['SDC_CLI_IDENTITY'] %>
  joyent_keyname: <%= ENV['SDC_CLI_KEY_ID'] %>
  joyent_url: <%= ENV['SDC_CLI_URL'] %>
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  flavor_id: <%= ENV['EC2_FLAVOR_ID'] %>
  availability_zone: <%= ENV['AWS_AVAILABILITY_ZONE'] %>

provisioner:
  name: chef_zero
  # require_chef_omnibus: 11.16.4
  # require_chef_omnibus: 12.0.3
  require_chef_omnibus: 12.1.1

platforms:
- name: centos-5.8
  driver_plugin: digital_ocean
  driver_config:
    size: 2gb
    image: centos-5-8-x64
    region: <%= ENV['DIGITAL_OCEAN_REGION'] %>
    ssh_key_ids: <%= ENV['DIGITAL_OCEAN_SSH_KEY_IDS'] %>
    ssh_key: <%= ENV['DIGITAL_OCEAN_SSH_KEY_PATH'] %>

- name: centos-6.5
  driver_plugin: digital_ocean
  driver_config:
    size: 2gb
    image: centos-6-5-x64
    region: <%= ENV['DIGITAL_OCEAN_REGION'] %>
    ssh_key_ids: <%= ENV['DIGITAL_OCEAN_SSH_KEY_IDS'] %>
    ssh_key: <%= ENV['DIGITAL_OCEAN_SSH_KEY_PATH'] %>

- name: centos-7.0
  driver_plugin: digital_ocean
  driver_config:
    size: 2gb
    image: centos-7-0-x64
    region: <%= ENV['DIGITAL_OCEAN_REGION'] %>
    ssh_key_ids: <%= ENV['DIGITAL_OCEAN_SSH_KEY_IDS'] %>
    ssh_key: <%= ENV['DIGITAL_OCEAN_SSH_KEY_PATH'] %>

- name: amazon-2014.09
  driver_plugin: ec2
  driver_config:
    image_id: ami-9a6ed3f2
    username: ec2-user
    ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>

# - name: redhat-6.5
#   driver_plugin: ec2
#   driver_config:
#     image_id: ami-8d756fe4
#     username: ec2-user
#     ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
#   run_list:
#   - recipe[selinux::disabled]

# - name: redhat-7.0
#   driver_plugin: ec2
#   driver_config:
#     image_id: ami-a8d369c0
#     username: ec2-user
#     ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
#   run_list:
#   - recipe[selinux::disabled]

- name: fedora-20
  driver_plugin: digital_ocean
  driver_config:
    size: 2gb
    image: fedora-20-x64
    region: <%= ENV['DIGITAL_OCEAN_REGION'] %>
    ssh_key_ids: <%= ENV['DIGITAL_OCEAN_SSH_KEY_IDS'] %>
    ssh_key: <%= ENV['DIGITAL_OCEAN_SSH_KEY_PATH'] %>

# - name: fedora-21
#   driver_plugin: digital_ocean
#   driver_config:
#     size: 2gb
#     image: fedora-21-x64
#     region: <%= ENV['DIGITAL_OCEAN_REGION'] %>
#     ssh_key_ids: <%= ENV['DIGITAL_OCEAN_SSH_KEY_IDS'] %>
#     ssh_key: <%= ENV['DIGITAL_OCEAN_SSH_KEY_PATH'] %>

# - name: suse-11.3
#   driver_plugin: ec2
#   driver_config:
#     image_id: ami-e8084981
#     username: root
#     ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>

- name: debian-7.0
  driver_plugin: gce
  driver_config:
    image_name: debian-7-wheezy-v20131120
    zone: <%= ENV['GCE_ZONE'] %>
    area: <%= ENV['GCE_AREA'] %>
    network: <%= ENV['GCE_NETWORK'] %>
    username: <%= ENV['GCE_USERNAME'] %>
    public_key_path: <%= ENV['GCE_PUBLIC_KEY_PATH'] %>
    ssh_key: <%= ENV['GCE_SSH_KEY_PATH'] %>
  run_list:
  - recipe[apt]

- name: ubuntu-10.04
  driver_plugin: digital_ocean
  driver_config:
    size: 2gb
    image: ubuntu-10-04-x64
    region: <%= ENV['DIGITAL_OCEAN_REGION'] %>
    ssh_key_ids: <%= ENV['DIGITAL_OCEAN_SSH_KEY_IDS'] %>
    ssh_key: <%= ENV['DIGITAL_OCEAN_SSH_KEY_PATH'] %>
  run_list:
  - recipe[apt]

- name: ubuntu-12.04
  driver_plugin: digital_ocean
  driver_config:
    size: 2gb
    image: ubuntu-12-04-x64
    region: <%= ENV['DIGITAL_OCEAN_REGION'] %>
    ssh_key_ids: <%= ENV['DIGITAL_OCEAN_SSH_KEY_IDS'] %>
    ssh_key: <%= ENV['DIGITAL_OCEAN_SSH_KEY_PATH'] %>
  run_list:
  - recipe[apt]

- name: ubuntu-14.04
  driver_plugin: digital_ocean
  driver_config:
    size: 2gb
    image: ubuntu-14-04-x64
    region: <%= ENV['DIGITAL_OCEAN_REGION'] %>
    ssh_key_ids: <%= ENV['DIGITAL_OCEAN_SSH_KEY_IDS'] %>
    ssh_key: <%= ENV['DIGITAL_OCEAN_SSH_KEY_PATH'] %>
  run_list:
  - recipe[apt]

# - name: omnios-151006
#   driver_plugin: ec2
#   driver_config:
#     image_id: ami-35eb835c
#     flavor_id: m3.large
#     username: root
#     ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
#   run_list:
#   - recipe[ips-omniti]

# - name: smartos-14.3.0
#   driver_plugin: joyent
#   driver_config:
#     joyent_image_id: 62f148f8-6e84-11e4-82c5-efca60348b9f
#     joyent_flavor_id: g3-standard-4-smartos
#     username: root
#     ssh_key: <%= ENV['SDC_CLI_IDENTITY'] %>
#   busser:
#     ruby_bindir: '/opt/local/bin/'
#   provisioner:
#     sudo: false
#     chef_omnibus_url: https://raw.github.com/test-kitchen/kitchen-joyent/master/scripts/install-smartos.sh

suites:
  #
  # service22-single
  #
  - name: service22-single
    run_list:
    - recipe[httpd_service_test::single]
    includes: [
      'amazon-2014.09',
      'centos-5.8',
      'centos-6.5',
      'debian-7.0',
      'omnios-151006',
      'smartos-13.4.0',
      'ubuntu-10.04',
      'ubuntu-12.04',
      'ubuntu-13.10',
    ]
    attributes:
      httpd:
        version: '2.2'

  #
  # service22-multi
  #
  - name: service22-multi
    run_list:
    - recipe[httpd_service_test::multi]
    includes: [
      'amazon-2014.03',
      'centos-5.8',
      'centos-6.5',
      'debian-7.0',
      'omnios-151006',
      'smartos-13.4.0',
      'ubuntu-12.04',
    ]
    attributes:
      httpd:
        contact: 'bob@computers.biz'
        version: '2.2'
        service_name: 'multi'
        listen_ports: [ '81', '444' ]
        run_user: 'bob'
        run_group: 'bob'
        timeout: '1234'
        keepalive: false
        keepaliverequests: '5678'
        keepalivetimeout: '8765'
        mpm: 'prefork'
        startservers: '20'
        minspareservers: '20'
        minspareservers: '40'

  #
  # service24-single
  #
  - name: service24-single
    run_list:
    - recipe[httpd_service_test::single]
    includes: [
      'amazon-2014.09',
      'centos-7.0',
      'fedora-20',
      'fedora-21',
      'omnios-151006',
      'smartos-13.4.0',
      'ubuntu-14.04',
    ]
    attributes:
      httpd:
        version: '2.4'

  #
  # service24-multi
  #
  - name: service24-multi
    run_list:
    - recipe[httpd_service_test::multi]
    includes: [
      'amazon-2014.09',
      'centos-7.0',
      'fedora-20',
      'fedora-21',
      'omnios-151006',
      'smartos-13.4.0',
      'ubuntu-14.04',
    ]
    attributes:
      httpd:
        version: '2.4'
        service_name: 'multi'
        listen_ports: [ '81', '444' ]
        run_user: 'bob'
        run_group: 'bob'
        contact: 'alice@computers.biz'
        timeout: '1234'
        keepalive: false
        keepaliverequests: '5678'
        keepalivetimeout: '8765'
        mpm: 'prefork'
        startservers: '20'
        minspareservers: '20'
        minspareservers: '40'

  #
  # modules
  #
  - name: module22
    run_list:
    - recipe[httpd_module_test]
    includes: [
      'amazon-2014.09',
      'centos-5.8',
      'centos-6.5',
      'debian-7.0',
      'omnios-151006',
      'smartos-13.4.0',
      'ubuntu-10.04',
      'ubuntu-12.04'
    ]
    attributes:
      httpd:
        version: '2.2'

  - name: module24
    run_list:
    - recipe[httpd_module_test]
    includes: [
      'amazon-2014.09',
      'centos-7.0',
      'fedora-20',
      'fedora-21',
      'omnios-151006',
      'smartos-13.4.0',
      'ubuntu-14.04',
    ]
    attributes:
      httpd:
        version: '2.4'

  #
  # config
  #
  - name: config
    run_list:
    - recipe[httpd_config_test]

  #
  # hello_world_test
  #
  - name: hello_world_test
    run_list:
    - recipe[hello_world_test]