---
driver:
  name: vagrant
  customize:
    memory: 512
    cpuexecutioncap: 50

provisioner:
  name: chef_zero
  chef_omnibus_url: http://artifactory.trusted.visa.com:8080/visa-file/chef/install.sh
  roles_path: "test/integration/visa_pipeline/roles"
  environments_path: "test/integration/visa_pipeline/environments"
  data_bags_path: "test/integration/visa_pipeline/data_bags"


platforms:
  - name: centos-5.10
  - name: centos-6.5
  - name: ubuntu-12.04
  - name: ubuntu-13.10
  - name: ubuntu-14.04
  - name: fedora-18
  - name: fedora-19
  - name: fedora-20
  - name: debian-6.0.9
  - name: debian-7.2.0
  - name: debian-7.4

suites:
  - name: ulimit2
    run_list:
      - recipe[ulimit2::default]
    attributes:
      ulimit:
        params:
          default:
            nofile: 10240
            nproc:
              soft: 2048
          root:
            nofile:
              soft: 15360
              hard: 'unlimited'
          '@sysadmin':
            nproc:
              hard: 4096
